#!/usr/bin/env bash

page_url="$1"
if [[ "$page_url" =~ ^[0-9]+$ ]]; then
    page_url="http://www.vlive.tv/video/${page_url}"
elif [[ ! "$page_url" =~ ^http ]]; then
    echo "Usage: $0 <vlive-url>" >&2
    exit 1
fi

stream_url="$(youtube-dl --get-url "$page_url")"
if [[ "$stream_url" =~ vlive\.hls ]]; then
    video_stream_url="hls://${stream_url}"
    sub_stream_url="${video_stream_url/chunklist.m3u8*/subtitlelist_leng.m3u8}"
    sub_path="$(mktemp --suffix=.vtt)"
    livestreamer "$sub_stream_url" best -Q -f -o "$sub_path" &
    livestreamer "$video_stream_url" best \
        --hls-segment-threads=3 \
        --player="mpv --script-opts=vlive='$sub_path'"
    kill %
    rm "$sub_path"
elif [[ "$stream_url" =~ ^http ]]; then
    exec mpv "$stream_url"
else
    exit 1
fi
